#+title: Tests for heat_mpi program

# set basic options such as the prefix for test output files and the
# timeout before testy declares failure.
#+TESTY: TIMEOUT=30s
#+TESTY: PREFIX=heat
#+TESTY: USE_VALGRIND=0

# Set up a command to run valgrind under mpirun checking for a variety
# of errors but suppressing those coming from the mpi library
#+TESTY: export RUNVALGRIND='valgrind'
#+TESTY: RUNVALGRIND+=' --leak-check=full --show-leak-kinds=all --track-origins=yes'
#+TESTY: RUNVALGRIND+=' --suppressions=test_mpi.supp --error-exitcode=17'
#+TESTY: RUNVALGRIND+=' --keep-debuginfo=yes'
#+TESTY: CHECKRETURN=1

# Set the MPIOPTS variable - on Gradescope must allow oversubscription
# (only 1 proc available) and running as root (Docker containers run
# as root by default).
#+TESTY: source ./mpiopts.sh
#+TESTY: MPIOPTS+=" --oversubscribe --allow-run-as-root"

* Procs=1 Width=20
Runs heat_mpi with a few timesteps and a bar 20 wide on only a single
processor. Checks that the output matches that of the serial
program. No memory checking is done. 

NOTE: the program must exit / return with status 0 to pass.

#+TESTY: program='mpirun $MPIOPTS -np 1 ./heat_mpi 10 20 1'
#+BEGIN_SRC text
   |     0     1     2     3     4     5     6     7     8     9    10    11    12    13    14    15    16    17    18    19 
---+-------------------------------------------------------------------------------------------------------------------------
  0|  20.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  10.0 
  1|  20.0  35.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  30.0  10.0 
  2|  20.0  35.0  42.5  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  40.0  30.0  10.0 
  3|  20.0  31.2  42.5  46.2  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  45.0  40.0  25.0  10.0 
  4|  20.0  31.2  38.8  46.2  48.1  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  47.5  45.0  35.0  25.0  10.0 
  5|  20.0  29.4  38.8  43.4  48.1  49.1  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  48.8  47.5  41.2  35.0  22.5  10.0 
  6|  20.0  29.4  36.4  43.4  46.2  49.1  49.5  50.0  50.0  50.0  50.0  50.0  50.0  49.4  48.8  45.0  41.2  31.9  22.5  10.0 
  7|  20.0  28.2  36.4  41.3  46.2  47.9  49.5  49.8  50.0  50.0  50.0  50.0  49.7  49.4  47.2  45.0  38.4  31.9  20.9  10.0 
  8|  20.0  28.2  34.8  41.3  44.6  47.9  48.8  49.8  49.9  50.0  50.0  49.8  49.7  48.4  47.2  42.8  38.4  29.7  20.9  10.0 
  9|  20.0  27.4  34.8  39.7  44.6  46.7  48.8  49.4  49.9  49.9  49.9  49.8  49.1  48.4  45.6  42.8  36.2  29.7  19.8  10.0 
#+END_SRC

* Procs=1 Width=20 Valgrind
Same as test 1 except that heat_mpi is run under Valgrind to check for
memory problems. This requires the presence of the file test_mpi.supp,
a suppression file for Valgrind which will omit errors from OpenMPI or
the Linux Kernel.  Valgrind is set up to return exit code 17 if it
detects problems and output is shown if this happens. If no memory
errors are detected and the program returns exit code 0, the test is
passed. Since every run under Valgrind can produce different output,
there is no expected output for this, only checks for detection of
errors. 

#+TESTY: skipdiff=1
#+TESTY: program='mpirun $MPIOPTS -np 1 $RUNVALGRIND ./heat_mpi 10 20 1'
#+BEGIN_SRC text
#+END_SRC

* Procs=2 Width=20
Runs same specs as test 1 but with 2 processors. 

#+TESTY: program='mpirun $MPIOPTS -np 2 ./heat_mpi 10 20 1'
#+BEGIN_SRC text
   |     0     1     2     3     4     5     6     7     8     9    10    11    12    13    14    15    16    17    18    19 
---+-------------------------------------------------------------------------------------------------------------------------
  0|  20.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  10.0 
  1|  20.0  35.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  30.0  10.0 
  2|  20.0  35.0  42.5  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  40.0  30.0  10.0 
  3|  20.0  31.2  42.5  46.2  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  45.0  40.0  25.0  10.0 
  4|  20.0  31.2  38.8  46.2  48.1  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  47.5  45.0  35.0  25.0  10.0 
  5|  20.0  29.4  38.8  43.4  48.1  49.1  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  48.8  47.5  41.2  35.0  22.5  10.0 
  6|  20.0  29.4  36.4  43.4  46.2  49.1  49.5  50.0  50.0  50.0  50.0  50.0  50.0  49.4  48.8  45.0  41.2  31.9  22.5  10.0 
  7|  20.0  28.2  36.4  41.3  46.2  47.9  49.5  49.8  50.0  50.0  50.0  50.0  49.7  49.4  47.2  45.0  38.4  31.9  20.9  10.0 
  8|  20.0  28.2  34.8  41.3  44.6  47.9  48.8  49.8  49.9  50.0  50.0  49.8  49.7  48.4  47.2  42.8  38.4  29.7  20.9  10.0 
  9|  20.0  27.4  34.8  39.7  44.6  46.7  48.8  49.4  49.9  49.9  49.9  49.8  49.1  48.4  45.6  42.8  36.2  29.7  19.8  10.0 
#+END_SRC

* Procs=2 Width=20 Valgrind
Same as previous test but runs under Valgrind to check for memory problems.

#+TESTY: skipdiff=1
#+TESTY: program='mpirun $MPIOPTS -np 2 $RUNVALGRIND ./heat_mpi 10 20 1'
#+BEGIN_SRC text
#+END_SRC

* Procs=2 Width=20 No output
Checks same specs as previous tests but with output parameter 0 which
should generate no output.

#+TESTY: program='mpirun $MPIOPTS -np 2 ./heat_mpi 10 20 0'
#+BEGIN_SRC text
#+END_SRC

* Procs=2 Width=6
Run with 2 procs and 6 elements wide. This is a "minimum" case as each
proc has 3 elements but is still required to run correctly. 

#+TESTY: program='mpirun $MPIOPTS -np 2 ./heat_mpi 8 6 1'
#+BEGIN_SRC text
   |     0     1     2     3     4     5 
---+-------------------------------------
  0|  20.0  50.0  50.0  50.0  50.0  10.0 
  1|  20.0  35.0  50.0  50.0  30.0  10.0 
  2|  20.0  35.0  42.5  40.0  30.0  10.0 
  3|  20.0  31.2  37.5  36.2  25.0  10.0 
  4|  20.0  28.8  33.8  31.2  23.1  10.0 
  5|  20.0  26.9  30.0  28.4  20.6  10.0 
  6|  20.0  25.0  27.7  25.3  19.2  10.0 
  7|  20.0  23.8  25.2  23.4  17.7  10.0 
#+END_SRC

* Procs=2 Width=6 Valgrind
Same as previous test but runs under Valgrind to check for memory problems.

#+TESTY: skipdiff=1
#+TESTY: program='mpirun $MPIOPTS -np 2 $RUNVALGRIND ./heat_mpi 8 6 1'
#+BEGIN_SRC text
#+END_SRC

* Procs=4 Width=20
Run with 2 procs and 6 elements wide. This is a "minimum" case as each
proc has 3 elements but is still required to run correctly. 

#+TESTY: program='mpirun $MPIOPTS -np 4 ./heat_mpi 10 20 1'
#+BEGIN_SRC text
   |     0     1     2     3     4     5     6     7     8     9    10    11    12    13    14    15    16    17    18    19 
---+-------------------------------------------------------------------------------------------------------------------------
  0|  20.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  10.0 
  1|  20.0  35.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  30.0  10.0 
  2|  20.0  35.0  42.5  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  40.0  30.0  10.0 
  3|  20.0  31.2  42.5  46.2  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  45.0  40.0  25.0  10.0 
  4|  20.0  31.2  38.8  46.2  48.1  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  47.5  45.0  35.0  25.0  10.0 
  5|  20.0  29.4  38.8  43.4  48.1  49.1  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  48.8  47.5  41.2  35.0  22.5  10.0 
  6|  20.0  29.4  36.4  43.4  46.2  49.1  49.5  50.0  50.0  50.0  50.0  50.0  50.0  49.4  48.8  45.0  41.2  31.9  22.5  10.0 
  7|  20.0  28.2  36.4  41.3  46.2  47.9  49.5  49.8  50.0  50.0  50.0  50.0  49.7  49.4  47.2  45.0  38.4  31.9  20.9  10.0 
  8|  20.0  28.2  34.8  41.3  44.6  47.9  48.8  49.8  49.9  50.0  50.0  49.8  49.7  48.4  47.2  42.8  38.4  29.7  20.9  10.0 
  9|  20.0  27.4  34.8  39.7  44.6  46.7  48.8  49.4  49.9  49.9  49.9  49.8  49.1  48.4  45.6  42.8  36.2  29.7  19.8  10.0 
#+END_SRC

* Procs=4 Width=20 Valgrind
Same as previous test but runs under Valgrind to check for memory problems.

#+TESTY: skipdiff=1
#+TESTY: program='mpirun $MPIOPTS -np 4 $RUNVALGRIND ./heat_mpi 10 20 0'
#+BEGIN_SRC text
#+END_SRC

* Procs=4 Steps=30 Width=40 
Larger run with 4 procs, wider width, more timesteps.

#+TESTY: program='mpirun $MPIOPTS -np 4 ./heat_mpi 30 40 1'
#+BEGIN_SRC text
   |     0     1     2     3     4     5     6     7     8     9    10    11    12    13    14    15    16    17    18    19    20    21    22    23    24    25    26    27    28    29    30    31    32    33    34    35    36    37    38    39 
---+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  0|  20.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  10.0 
  1|  20.0  35.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  30.0  10.0 
  2|  20.0  35.0  42.5  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  40.0  30.0  10.0 
  3|  20.0  31.2  42.5  46.2  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  45.0  40.0  25.0  10.0 
  4|  20.0  31.2  38.8  46.2  48.1  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  47.5  45.0  35.0  25.0  10.0 
  5|  20.0  29.4  38.8  43.4  48.1  49.1  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  48.8  47.5  41.2  35.0  22.5  10.0 
  6|  20.0  29.4  36.4  43.4  46.2  49.1  49.5  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  49.4  48.8  45.0  41.2  31.9  22.5  10.0 
  7|  20.0  28.2  36.4  41.3  46.2  47.9  49.5  49.8  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  49.7  49.4  47.2  45.0  38.4  31.9  20.9  10.0 
  8|  20.0  28.2  34.8  41.3  44.6  47.9  48.8  49.8  49.9  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  49.8  49.7  48.4  47.2  42.8  38.4  29.7  20.9  10.0 
  9|  20.0  27.4  34.8  39.7  44.6  46.7  48.8  49.4  49.9  49.9  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  49.9  49.8  49.1  48.4  45.6  42.8  36.2  29.7  19.8  10.0 
 10|  20.0  27.4  33.5  39.7  43.2  46.7  48.0  49.4  49.6  49.9  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  49.9  49.5  49.1  47.4  45.6  40.9  36.2  28.0  19.8  10.0 
 11|  20.0  26.8  33.5  38.4  43.2  45.6  48.0  48.8  49.6  49.8  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  49.7  49.5  48.5  47.4  44.2  40.9  34.5  28.0  19.0  10.0 
 12|  20.0  26.8  32.6  38.4  42.0  45.6  47.2  48.8  49.3  49.8  49.9  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  49.9  49.7  49.1  48.5  46.3  44.2  39.3  34.5  26.8  19.0  10.0 
 13|  20.0  26.3  32.6  37.3  42.0  44.6  47.2  48.3  49.3  49.6  49.9  49.9  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  49.9  49.9  49.5  49.1  47.7  46.3  42.8  39.3  33.0  26.8  18.4  10.0 
 14|  20.0  26.3  31.8  37.3  40.9  44.6  46.4  48.3  48.9  49.6  49.8  49.9  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  49.9  49.7  49.5  48.6  47.7  45.3  42.8  37.9  33.0  25.7  18.4  10.0 
 15|  20.0  25.9  31.8  36.4  40.9  43.7  46.4  47.7  48.9  49.4  49.8  49.9  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  49.8  49.7  49.1  48.6  46.9  45.3  41.6  37.9  31.8  25.7  17.9  10.0 
 16|  20.0  25.9  31.1  36.4  40.0  43.7  45.7  47.7  48.5  49.4  49.6  49.9  49.9  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  49.9  49.8  49.5  49.1  48.0  46.9  44.3  41.6  36.7  31.8  24.8  17.9  10.0 
 17|  20.0  25.6  31.1  35.6  40.0  42.9  45.7  47.1  48.5  49.1  49.6  49.8  49.9  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  49.9  49.9  49.7  49.5  48.8  48.0  46.1  44.3  40.5  36.7  30.8  24.8  17.4  10.0 
 18|  20.0  25.6  30.6  35.6  39.2  42.9  45.0  47.1  48.1  49.1  49.4  49.8  49.9  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  49.9  49.8  49.7  49.2  48.8  47.5  46.1  43.3  40.5  35.6  30.8  24.1  17.4  10.0 
 19|  20.0  25.3  30.6  34.9  39.2  42.1  45.0  46.5  48.1  48.8  49.4  49.6  49.9  49.9  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  49.9  49.8  49.5  49.2  48.3  47.5  45.4  43.3  39.5  35.6  29.9  24.1  17.0  10.0 
 20|  20.0  25.3  30.1  34.9  38.5  42.1  44.3  46.5  47.6  48.8  49.2  49.6  49.8  49.9  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  49.9  49.9  49.7  49.5  48.9  48.3  46.9  45.4  42.4  39.5  34.7  29.9  23.5  17.0  10.0 
 21|  20.0  25.0  30.1  34.3  38.5  41.4  44.3  46.0  47.6  48.4  49.2  49.5  49.8  49.9  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  49.9  49.8  49.7  49.3  48.9  47.9  46.9  44.6  42.4  38.5  34.7  29.1  23.5  16.7  10.0 
 22|  20.0  25.0  29.7  34.3  37.9  41.4  43.7  46.0  47.2  48.4  49.0  49.5  49.7  49.9  49.9  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  49.9  49.8  49.6  49.3  48.6  47.9  46.3  44.6  41.6  38.5  33.8  29.1  22.9  16.7  10.0 
 23|  20.0  24.8  29.7  33.8  37.9  40.8  43.7  45.5  47.2  48.1  49.0  49.3  49.7  49.8  49.9  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  49.9  49.9  49.7  49.6  49.1  48.6  47.4  46.3  43.9  41.6  37.7  33.8  28.3  22.9  16.4  10.0 
 24|  20.0  24.8  29.3  33.8  37.3  40.8  43.1  45.5  46.8  48.1  48.7  49.3  49.6  49.8  49.9  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  49.9  49.8  49.7  49.4  49.1  48.3  47.4  45.7  43.9  40.8  37.7  33.0  28.3  22.4  16.4  10.0 
 25|  20.0  24.6  29.3  33.3  37.3  40.2  43.1  44.9  46.8  47.7  48.7  49.1  49.6  49.7  49.9  49.9  50.0  50.0  50.0  50.0  50.0  50.0  50.0  50.0  49.9  49.8  49.6  49.4  48.8  48.3  47.0  45.7  43.3  40.8  36.9  33.0  27.7  22.4  16.2  10.0 
 26|  20.0  24.6  29.0  33.3  36.7  40.2  42.6  44.9  46.3  47.7  48.4  49.1  49.4  49.7  49.8  49.9  50.0  50.0  50.0  50.0  50.0  50.0  50.0  49.9  49.9  49.8  49.6  49.2  48.8  47.9  47.0  45.1  43.3  40.1  36.9  32.3  27.7  22.0  16.2  10.0 
 27|  20.0  24.5  29.0  32.9  36.7  39.7  42.6  44.5  46.3  47.4  48.4  48.9  49.4  49.6  49.8  49.9  50.0  50.0  50.0  50.0  50.0  50.0  50.0  49.9  49.9  49.8  49.5  49.2  48.6  47.9  46.5  45.1  42.6  40.1  36.2  32.3  27.1  22.0  16.0  10.0 
 28|  20.0  24.5  28.7  32.9  36.3  39.7  42.1  44.5  45.9  47.4  48.2  48.9  49.3  49.6  49.8  49.9  49.9  50.0  50.0  50.0  50.0  50.0  50.0  49.9  49.9  49.7  49.5  49.0  48.6  47.5  46.5  44.6  42.6  39.4  36.2  31.7  27.1  21.6  16.0  10.0 
 29|  20.0  24.3  28.7  32.5  36.3  39.2  42.1  44.0  45.9  47.0  48.2  48.7  49.3  49.5  49.8  49.8  49.9  50.0  50.0  50.0  50.0  50.0  49.9  49.9  49.8  49.7  49.4  49.0  48.3  47.5  46.1  44.6  42.0  39.4  35.5  31.7  26.6  21.6  15.8  10.0 
#+END_SRC

